### ISSUE TITLE
ldd-like functionality?

### ISSUE THREAD

**Issue by probonopd** [aep/elfkit#11]
For https://github.com/probonopd/linuxdeployqt I am looking for a `ldd` replacement that could show library dependencies _independently of the architecture of the currently running system_ (for cross-compilations). Can elfkit do this or could `ldd`-like functionality be added to it?

**Comment by aep** [comment]
nice project! About time someone does macdpeloyqt for linux :)
Here's how i do exactly what you need in archon (an image packager for elf binaries):

https://github.com/korhalio/archon/blob/4132ac180fb4b55a858bfa835f28a137a5eaa675/src/build.rs#L27

essentially you iterate through each section, finding the one thats elfkit::types::SectionType::DYNAMIC.
for each entry in that dynamic section, filter out the NEEDED entries. those are what ldd shows.

note that this does of course not work on plugins, but you probably know that.

**Comment by probonopd** [comment]
> nice project! About time someone does macdpeloyqt for linux :)

Thanks :-)

> Here's how i do exactly what you need in archon (an image packager for elf binaries):
> essentially you iterate through each section, finding the one thats elfkit::types::SectionType::DYNAMIC.
for each entry in that dynamic section, filter out the NEEDED entries. those are what ldd shows.

:+1: Is there any chance this could be made into a standalone executable that could easily be consumed as a replacement for the `ldd` command (say, `elfkit-ldd`)?

> note that this does of course not work on plugins, but you probably know that.

Indeed. `linuxdeployqt` has its own logic for those.

**Comment by aep** [comment]
> there any chance this could be made into a standalone executable that could easily be consumed as a 
   replacement for the ldd command?

should be fairly easy to do. do you have any preferred output format?

**Comment by probonopd** [comment]
The same output format as the normal `ldd` would be preferred, because then it could be used in place of `ldd` within existing applications that would not need to be changed.

---

By the way somehow I have the feeling that you know a lot about ELF files that could be a great fit for the [AppImage](https://appimage.org/) project. Among others, we have to deal with glibc backward compatibility issues and are looking for efficient ways to deduplicate, delta-update, and peer-to-peer distribute AppImages (squashfs files containing ELF binaries and ELF libraries...)

**Comment by aep** [comment]
i don't have automated stasis builds setup yet, so try this one for now:
[ek-ldd.zip](https://github.com/aep/elfkit/files/1589192/ek-ldd.zip)

```
$ ./ldd /bin/bash /usr/lib
/usr/lib/libreadline.so.7
/usr/lib/libncursesw.so.6
/usr/lib/libc.so.6
/usr/lib/ld-linux-x86-64.so.2
/usr/lib/libtinfo.so.6
/usr/lib/libdl.so.2
```

ldd needs to be able to find the libraries for recursive lookup, so add your sysroots library paths as additional arguments. Let me know if you prefer a different method

--

i quickly had a look at appimage and it definitely is the right idea. this should help alot of companies create better packages, especially for proprietary games.

I'll be happy to answer any questions you have on ELF, linking, loading etc. My company korhal.io is located in Berlin/Ritterstrasse. my email is arvid@korhal.io . Drop me an email if you want to hang out. We do some pretty wild stuff that probably aligns well with app-image.  note how the binary i sent you has absolutely no dependencies. not even to libc.

**Comment by probonopd** [comment]
Thank you very much for this super useful tool. Do you think you could make it observe `/etc/ld.so.conf` to figure out the library paths? (Not a big thing otherwise, I am sure I could script around it.)

```
# This crashes:
$ Downloads/ldd /bin/bash 
thread 'main' panicked at 'unable to find dependcy libtinfo.so.5 in ["/lib", "/usr/lib"]', bin/ldd.rs:43:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

# This works:
$ Downloads/ldd /bin/bash /usr/lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/
/lib/x86_64-linux-gnu/libtinfo.so.5
/lib/x86_64-linux-gnu/libc.so.6
/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
/lib/x86_64-linux-gnu/libdl.so.2
```

So one needs to pass in the paths to libraries (which one can determine from parsing `/etc/ld.so.conf`).

The next example is a bit harder as it requires knowledge of ELF internals - any chance you could make it work?

```
$ Downloads/ldd /usr/bin/pulseaudio  /usr/lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/
/lib/x86_64-linux-gnu/libsystemd.so.0
(...)
thread 'main' panicked at 'unable to find dependcy libpulsecore-8.0.so in ["/usr/lib/x86_64-linux-gnu/", "/lib/x86_64-linux-gnu/"]', bin/ldd.rs:43:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ ldd /usr/bin/pulseaudio
	(...)
	libpulsecore-8.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecore-8.0.so (0x00007fd80f5ff000)

$ patchelf --print-rpath /usr/bin/pulseaudio
/usr/lib/x86_64-linux-gnu/pulseaudio
```

Do you think you could build in rpath/runpath support?

---

Yes, I noticed the interesting work you are doing. Definitely will watch the videos and drop you a note if I happen to be in Berlin.

**Comment by aep** [comment]
both of those would require knowing the sysroot, and would assume that the sysroot is ubuntu style. If that's ok for you i'll add a --sysroot option that will cover both.

**Comment by probonopd** [comment]
Yes, that'd be awesome. Thank you! :+1:

**Comment by aep** [comment]
that should do it. although i didnt read the ld code that parses ld.so.conf so there might be more features than "include". let me know if something doesnt work.
[ek-ldd-2.zip](https://github.com/aep/elfkit/files/1589598/ek-ldd-2.zip)


```
./ldd -R /tmp/j/k /bin/bash                                       
/tmp/j/k/usr/lib/libreadline.so.7                                        
/tmp/j/k/usr/lib/libncursesw.so.6
/tmp/j/k/usr/lib/libc.so.6
/tmp/j/k/usr/lib/ld-linux-x86-64.so.2
/tmp/j/k/usr/lib/libtinfo.so.6
/tmp/j/k/usr/lib/libdl.so.2

```

**Comment by probonopd** [comment]
Looks like it isn't picking up RPATHs:

```
$ Downloads/ldd /usr/bin/pulseaudio -R /
//lib/x86_64-linux-gnu/libsystemd.so.0
//lib/x86_64-linux-gnu/libselinux.so.1
//lib/x86_64-linux-gnu/libpcre.so.3
//lib/x86_64-linux-gnu/libpthread.so.0
//lib/x86_64-linux-gnu/libc.so.6
//lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
//lib/x86_64-linux-gnu/libdl.so.2
//lib/x86_64-linux-gnu/librt.so.1
//lib/x86_64-linux-gnu/liblzma.so.5
//lib/x86_64-linux-gnu/libgcrypt.so.20
//lib/x86_64-linux-gnu/libgpg-error.so.0
thread 'main' panicked at 'unable to find dependcy libpulsecore-8.0.so in ["//usr/local/lib", "//lib/x86_64-linux-gnu", "//usr/lib/x86_64-linux-gnu", "//usr/lib/x86_64-linux-gnu/mesa-egl", "//usr/lib/x86_64-linux-gnu/mesa"]', bin/ldd.rs:49:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is where the library is located:

```
$ patchelf --print-rpath /usr/bin/pulseaudio 
/usr/lib/x86_64-linux-gnu/pulseaudio
```

**Comment by aep** [comment]
@probonopd oh sorry, forgot to implement that. here you go.

[ek-ldd-3.zip](https://github.com/aep/elfkit/files/1590881/ek-ldd-3.zip)

**Comment by aep** [comment]
also -R is optional. / is the default

**Comment by probonopd** [comment]
Thank you very much. Highly appreciated. :+1:
