### ISSUE TITLE
The 0.0.4 version on crates.io differs from 0.0.4 git tag

### ISSUE THREAD

**Issue by konstin** [aep/elfkit#13]
The 0.0.4 release on crates.io is completely different to the git(hub) version. For the example the Cargo.toml isn't the one from the 0.0.4 tag, but from somewhere between the 0.0.3 and 0.0.4 tag: https://github.com/aep/elfkit/blob/13fccbf8cae159470c38016e640b4671e6eaf3cc/Cargo.toml. I'd assume that somehow an old version accidentally got published on crates.io as 0.0.4

**Comment by aep** [comment]
good catch!
i did the 0.4 tag to attach a binary for someone who asked, but forgot to update it later.

**Comment by aep** [comment]
0.0.5 should now be properly done :)

**Comment by konstin** [comment]
Thank you!
